### ISSUE TITLE
Use case on new Logo

### ISSUE THREAD

**Issue by kidboy-man** [ilmonteux/project-phishing#4]
If I want to use logohunter to identify a completely new logo on images, will it work?
if yes, then which part should I tune?

**Comment by ilmonteux** [comment]
Hi there,
Yes, let's say that you have a bunch of images in a folder and you want to check for a particular logo (never seen before, not in training set), then the general syntax is
```
python logohunter.py  --image  --input_brands <path_to_logo_image> \
                                                    --input_images  <path_to_images_folder> \
                                                    --output <output_folder>  --outtxt
```
This will look for the input logo in the folder of images passed and yields inference images with bounding boxes in the output folder as well as a txt file with the bounding boxes coordinates for each image.

In my testing, this should give about 90% precision and about 50% recall for a general logo, with some variation depending how difficult the logo is. 

For tuning the model, there are some knobs that don't require re-training the model (for example, passing the `--fpr` option in `logohunter.py` will change the precision threshold. See the `src/` directory for more details). Another option is to retrain the feature extraction model (InceptionV3 or VGG16), so that the feature extracted are more relevant to understanding logo similarity (for example, it could be trained on logo classification). Finally, one could also retrain the logo extractor (the YOLOv3 network).
