### ISSUE TITLE
Logos it has not seen before

### ISSUE THREAD

**Issue by earlng** [ilmonteux/project-phishing#7]
Hi ilmonteux!

Thanks for this repo! It is awesome.

I just finished spinning up a demo environment following your instructions. Very clean, everything is working!

I do have a conceptual question on how this model behaves, specifically on logos the model has never seen before. I ran my own test using images I pulled of Toyota cars (similar to your Lexus example, but using Toyota cars and logo instead).

The model was able to accurately point out what it thought were logos, but it only identified the logo as "toyota" twice (out of like 8 logos). Reviewing the text output, it said something like:

`../logohunter/data/test/toyota/t4.jpg`
`../logohunter/data/test/toyota/t2.jpg`
`../logohunter/data/test/toyota/t6.jpg 31,531,301,584,toyota,0.20,0.948 740,71,821,131,toyota,0.97,0.998`
`../logohunter/data/test/toyota/t1.jpg`

And then I realized that I never quite outright told the model the logo was toyota. I imagine toyota was part of the training dataset, so it knows. (Note: these other images were flagged as logos, but just not toyota)

But what happens if I were to give it some random niche logo that it probably never saw before? I imagine it would still identify it as a logo, but would not produce a log entry like above?

Edit: this data output: `31,531,301,584,toyota,0.20,0.948`, I assume what this means is that the 0.20 is how confident that it is a "toyota" logo (compared to the training dataset), and 0.948 is how similar it is to the input image I gave? -> this was why I wanted to ask, what if the input image was something it doesn't have a label for?

**Comment by ilmonteux** [comment]
Hey, 
the main goal of the model is to detect logos it has never seen before by first detecting logos as a general concept and then matching the found logo to the input you passed it (by comparing similarities between the features extracted by the classifier step - e.g. Inceptionv3).

So in your example when it found logos but it didn't recognize them as toyota, it's because it failed in the second step, the similarity between the found logo and the input you passed wasn't high enough. That's expected to happen, the recall I was getting was usually around 40-60% on new logos (like in the test folder), also because we are optimizing for precision when setting the similarity cutoff. Note that the similarity cutoff that those logos don't pass is calculated based on an expected precision target (`sim_threshold = 0.95` is set [here](https://github.com/ilmonteux/logohunter/blob/master/src/logohunter.py#L18), and the similarity cutoff based on the expected precision is calculated [here](https://github.com/ilmonteux/logohunter/blob/master/src/logohunter.py#L190)) by comparing the input logo to all the logos in LogosInTheWild database: if you lowered that you'd get more false positives (for example, a nike logo being matched to your toyota logo target), but would also increase your recall (lower your False Negatives). Also I just realized that I have a CLI option `--fpr` that was intended to replace the global `sim_threshold` setting above, but I forgot to pass it (as `sim_threshold = 1 - fpr`) to the `load_brands_compute_cutoffs` function.

Now for how does the model know it's toyota (in the output bounding box image, and output txt) it really doesn't: it's just picking the label name from the filename of the input you passed, in [here](https://github.com/ilmonteux/logohunter/blob/master/src/logohunter.py#L177): so if the input was `test_banana.xyz` it would have returned `banana` instead of `toyota`. 

For the data output, you have it almost right: in `31,531,301,584,toyota,0.20,0.948`, `0.20` is the YOLO score for a logo (how confident the model is that there is a logo), while `0.948` is how confident we are that the found logo is a toyota logo. More technically, it's the percentile of the similarity score between the found logo and the toyota logo (that you passed as input), calculated given the CDF of similarity scores between the LogosInTheWild logos and the toyota logo. This CDF is computed in [`load_brands_compute_cutoffs` here](https://github.com/ilmonteux/logohunter/blob/master/src/similarity.py#L43) and the percentile calculation is in [`similar_matches` here](https://github.com/ilmonteux/logohunter/blob/master/src/similarity.py#L95). So in that case, 94.8% of "any other logo" (=LogosInTheWild) looks less similar to your input than the one it found.

Finally, it's true that `toyota` was actually in the LogosInTheWild database (with about 30 samples, [see here](https://github.com/ilmonteux/logohunter/blob/master/notebooks/logo_brands_dist.png)), and so it appears in the training dataset and in the CDF mentioned above, so there is some leaking, but because it's 30 samples in 30k logos I wouldn't expect nothing to change much. The variety of the LogosInTheWild database is pretty great and ensures that the model is more generalizable.

**Comment by earlng** [comment]
Ahh ok, I understand now, thank you so much for the detailed explanation! Again, kudos on the great implementation and documentation!
