### ISSUE TITLE
re-training the model

### ISSUE THREAD

**Issue by earlng** [ilmonteux/project-phishing#8]
Hi ilmonteux,

I was just wondering, for the re-training instructions you specified [here](https://github.com/ilmonteux/logohunter#optional-train-object-detection-model) and [here](https://github.com/ilmonteux/logohunter/blob/master/data/README.md). Would following this process with my own dataset produce _both_  the YOLOv3 and INCEPTIONv3 models? Or only the YOLOv3?

I'm primarily asking, because from my testing (with my own random images), your pre-trained model is doing very well in identifying *a logo*. But seems to be underperforming in rating the level of similarity to the input image. So I was wondering fi a retrain of the INCEPTIONv3 would resolve this.

Thank you!

**Comment by ilmonteux** [comment]
That would only retrain the YOLO model. You are correct that retraining the inception model on more relevant data (instead of ImageNet) would likely increase the performance for logo similarity. For example, it could be fine-tuned on a dataset made by taking the logo cut-outs from the Logosinthewild dataset (the `data_cleaned/brandROIs` folders mentioned [here](https://github.com/ilmonteux/logohunter/blob/master/data/README.md)). The features extracted at the end of the encoder layers would then be more relevant to distinguish logos, so the similarity step should achieve better performance

**Comment by earlng** [comment]
I see, right, so the model you use for the Inception model is `inception_logo_features.hdf5`, which we download from your S3 bucket as part of the `build.sh`. I looked through your repo, but couldn't find any instruction on how to train an inception model. Do you have any notes for that? or point me in the right direction?

**Comment by ilmonteux** [comment]
For re-training the feature extractor, you will have to train the model on a logo dataset, instead of using the one pre-trained on ImageNet that comes with keras. Instead of retraining the whole model, you can probably just fine-tune it (by freezing most layers up to the very end, for example [see this guide](https://towardsdatascience.com/cnn-transfer-learning-fine-tuning-9f3e7c5806b2) (the fine-tuning section)).
If you got the logos from the LogosInTheWild authors and followed the instructions in the `data/` folder, after running [src/create_clean_dataset.py](../blob/master/src/create_clean_dataset.py) you have a `data/LogosInTheWild-v2/data_cleaned/brandROIs` folder that contains truth-level logos extracted from the features, which should be great for fine-tuning the feature extractor. The job there would be to associate each logo to its class, and the last layers of the model would learn more logo-specific combinations of high-level features from the frozen layers. This should help with the similarity comparison (which is just the simplest decision function).

Note that re-training even the last layers of a huge model like Inception might be very hard to do even on a GPU machine. You could try a simpler model like a VGG16 first (check out `load_extractor_model` and `model_flavor_from_name` in [src/utils.py](../blob/master/src/utils.py#L36) for models and different truncations I tried, those can be called via the `--features` flag in `logohunter.py`).

**Comment by earlng** [comment]
I see, thank you so much for the advice!
